fixtures:
  repositories:
    'common':
      repo: 'https://github.com/ghoneycutt/puppet-module-common.git'
      ref:  'v1.3.0'
    'stdlib':
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
  symlinks:
    afs: "#{source_dir}"
