fixtures:
  repositories:
    'common':
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref:  'v1.0.2'
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '3.2.0'
    'stdlibfeatures':
      repo: 'git://github.com/ghoneycutt/puppet-module-stdlibfeatures.git'
      ref:  'v0.1.0'
  symlinks:
    afs: "#{source_dir}"
