.travis.yml:
  branches:
    - main
    - /^v\d/
    - master
spec/spec_helper.rb:
  hiera_config: 'hiera'
  mock_with: ':rspec'
Gemfile:
  required:
    ':development':
      - gem: github_changelog_generator
Rakefile:
  extras:
    - "require 'github_changelog_generator/task'"
    - 'GitHubChangelogGenerator::RakeTask.new :changelog do |config|'
    - '  version = (Blacksmith::Modulefile.new).version'
    - '  config.exclude_labels = %w{duplicate question invalid wontfix modulesync}'
    - 'end'
