name         'puppet-module-afs'
version      '1.0.3'
source       'ssh://gerrit.ericsson.se:29418/puppet/puppet-module-afs'
author       'phil.friderici@ericsson.com'
license      'Apache License, Version 2.0'
summary      'Manage OpenAFS'
description  'Manage OpenAFS'
project_page 'https://gerrit.ericsson.se/#/admin/projects/puppet/puppet-module-afs'

dependency 'puppetlabs/stdlib',        '>= 4.2.0'
dependency 'ghoneycutt/common',        '>= 1.0.0'
dependency 'ghoneycutt/stdlibfeatures','>= 0.1.0'
