name         'puppet-module-afs'
version      '1.2.0'
source       'git://github.com:Phil-Friderici/puppet-module-afs.git'
author       'phil.friderici@ericsson.com'
license      'Apache-2.0'
summary      'Manage OpenAFS'
project_page 'https://github.com/Phil-Friderici/puppet-module-afs'

dependency 'puppetlabs/stdlib',        '>= 4.2.0'
dependency 'ghoneycutt/common',        '>= 1.0.0'
