name         'phil-friderici-afs'
version      '0.2.0'
source       'git@github.com:Phil-Friderici/puppet-module-afs.git'
author       'Phil-Friderici'
license      'Apache License, Version 2.0'
summary      'Manage OpenAFS'
description  'Manage OpenAFS'
project_page 'https://github.com/Phil-Friderici/puppet-module-afs'

dependency 'puppetlabs/stdlib',        '>= 3.2.0'
dependency 'ghoneycutt/common',        '>= 1.0.0'
dependency 'ghoneycutt/stdlibfeatures','>= 0.1.0'
